### ISSUE TITLE
SNYK still detects issues with `test/go.mod`

### ISSUE THREAD

**Issue by helenakallekleiv** [equinor/terraform-azurerm-service-bus#12]
SNYK monitoring still detects issues regarding packages in `test/go.mod`.

Summary of issues:
- 12 issues detected
- Severity levels:  4 high, 6 medium, 2 low
- All issues are regarding dependencies within the packages included in `go.mod` 
- SNYK categorizes the issues as having "No supported fix"

A fix for this was attempted in #10, which decreased the number of issues but did not completely mitigate them.

Ref. SNYK Dashboard: https://app.snyk.io/org/cyclops-qou/project/62043ec8-448a-48cd-9a60-3f76a9f422a5

**Comment by chbul** [comment]
### Individual issues
- [ ] #11

**Comment by sebastianlolv** [comment]
Fixed alot of them in: https://github.com/equinor/terraform-azurerm-service-bus/pull/26

Still 2 vulnerabilities. 

First vulnerability:
github.com/satori/go.uuid - Insecure Randomness is introduced through github.com/gruntwork-io/terratest@v0.46.7, but fixed in github.com/satori/go.uuid commit d91630c8510268e75203009fe7daf2b8e1d60c45. Hopefully gruntwork pushes an update to terratest with the fix soon.

Second vulnerability:
github.com/docker/cli - Credential Exposure is also introduced through github.com/gruntwork-io/terratest@v0.46.7. Still waiting for a new version of terratest fixing this issue as vulnerability was fixed in 
github.com/docker/cli@20.10.9.

**Comment by hknutsen** [comment]
Consider migrating to native Terraform test functionality instead: https://developer.hashicorp.com/terraform/tutorials/configuration-language/test

**Comment by helenakallekleiv** [comment]
SNYK continue to report issues related to the `go.mod` packages. Upgrading the packages only mitigates the issues temporarily.

Related to @hknutsen's comment, I've created an issue in `terraform-baseline` relaying this.
- https://github.com/equinor/terraform-baseline/issues/98

**Comment by sebastianlolv** [comment]
There will always be new vulnerabilities, especially with the amount of packages in `go.mod`. This issue will probably stay up forever 😄 

Testing with latest Go version triggers Windows Defender, so migrating to native Terraform test is a good idea.
